### PR TITLE
Add tests for :scoped feature in friendly_id-mobility

### PR DESCRIPTION
**Pull request by bricesanchez**
Hi @shioyama !

It looks like the `:scoped` feature works well with Mobility.

### CODE REVIEW

**Comment by shioyama** [comment]
Thanks! Will have a look later today.

**Comment by shioyama** [comment]
Merged in f5d952fd95955ff91f377d1efec2f91b6b822440, thanks!

**Comment by bricesanchez** [comment]
You're welcome !

**Comment by andreierdoss** [comment]
Scoped does not work for me. I am using it in a self referential relationship ie. categories with sub categories and I am scoping on the parent.

`
class Location < ApplicationRecord
  belongs_to :parent, class_name: 'Location', optional: true
  has_many :children, class_name: 'Location', foreign_key: 'parent_id'
  
  extend Mobility
  translates :name, :slug, dirty: true

  extend FriendlyId
  friendly_id :name, use: [:mobility, :scoped], scope: :parent
end`

Please let me know if I am missing something. The slug created are only the name without the parent.

**Comment by bricesanchez** [comment]
Hi @andreierdoss, 

What if you add `:mobility` at first position?

`friendly_id :name, use: [:mobility, :scoped], scope: :parent`

**Comment by shioyama** [comment]
I'm not really familiar with `scoped`, but probably you'll need to make the Mobility scope default:

```ruby
class Category < ApplicationRecord
  default_scope { i18n }
  # ...
end
```

If this still does not work, then please make a PR with a failing spec. That should make it easier to identify the issue.

**Pull request closed without merging**
