### PR TITLE
Generate all translated slugs when model is saved

### PR DESCRIPTION
**Pull request by shioyama**
Added a test for #10

### CODE REVIEW

**Comment by n-rodriguez** [comment]
@shioyama I've just checked and it partially works. It still needs patch on `should_generate_new_friendly_id?` method.

**Comment by shioyama** [comment]
> @shioyama I've just checked and it partially works. It still needs patch on `should_generate_new_friendly_id?` method.

Ah I can fix that too. Hold on I'll push another commit.

**Comment by shioyama** [comment]
> It still needs patch on `should_generate_new_friendly_id?` method.

Actually I'm not sure the issue with this one, can you clarify?

**Comment by n-rodriguez** [comment]
I was referring to https://github.com/shioyama/friendly_id-mobility/issues/10#issuecomment-403999985
To make the first test pass you need to uncomment `should_generate_new_friendly_id?` and `translation_for` patched methods.
To make the second test pass you need to uncomment the `set_slug` patched method.

**Comment by shioyama** [comment]
Ah so the problem seems to be fallbacks...

**Comment by n-rodriguez** [comment]
> Ah so the problem seems to be fallbacks...

Yes

**Comment by shioyama** [comment]
Ok I added 9cb5194 which seems to fix the specs. The problem was that `should_generate_new_friendly_id?` was calling the slug attribute method, which was falling back so it seemed like it didn't need to regenerate the slug. By instead calling `slug(locale: Mobility.locale)` Mobility ignores fallbacks, which fixes the issues.

**Comment by n-rodriguez** [comment]
Awesome! It works!

**Comment by shioyama** [comment]
This has been released as 0.5.4. Thanks for your help!

**Comment by n-rodriguez** [comment]
> This has been released as 0.5.4. Thanks for your help!

You're welcome! Thanks for this gems!

**Pull request merged**
